### PR TITLE
Tip.party Rebranding

### PR DESCRIPTION
**Pull request by ghostffcode**

### CODE REVIEW

**Comment by over9001** [comment]
Nice! When I search tips in this repo I also find
packages/react-app/src/views/Admin.jsx
line 184 ?

**Review by codenamejason — APPROVED** [review]
👀  good. We can also keep an eye out during our travels.

**Comment by ghostffcode** [comment]
> Nice! When I search tips in this repo I also find
> packages/react-app/src/views/Admin.jsx
> line 184 ?

Thanks for pointing that out, changed that now.

**Pull request merged**
