### PR TITLE
[issue-276] Added Join Room and Create Room Button

### PR DESCRIPTION
**Pull request by farque65**
- User is set as Guest when Join Room is clicked
- User is set as Host when Create Room is clicked

### CODE REVIEW

**Comment by varunv5000** [comment]
Still an issue where toggle button doesn't load immediately when entering a room

**Comment by farque65** [comment]
> Still an issue where toggle button doesn't load immediately when entering a room

This is still in progress

**Comment by varunv5000** [comment]
Same issue as before, the button does not show up until later. Is there any other workaround?

**Comment by varunv5000** [comment]
Feel that the issue is with this line in App.jsx:
The button probably only loads when the url is completely loaded

const room = window.location.pathname.slice(6);

**Comment by farque65** [comment]
It should be faster since the Browser Router was moved up. I deployed the site to surge and it was faster

**Review by varunv5000 — APPROVED** [review]
Will merge, but bug should still be fixed for later

**Pull request merged**
