### PR TITLE
Added Tailwindcss and Responsive Navbar

### PR DESCRIPTION
**Pull request by farque65**
- Configure Tailwindcss
- Make navbar responsive
- Some clean up

### CODE REVIEW

**Comment by varunv5000** [comment]
Seems like a good start, but I don't think having a centered navbar looks good on desktop. I think we should first make the upgrades to the functionalities, then we can add new designs + mobile-optimized UI.

**Comment by farque65** [comment]
This has minimal design updates, this is not a redesign. The biggest change is adding tailwindcss, it will make developing the front end easier. The navbar will be easier to use on mobile.

**Comment by varunv5000** [comment]
Okay, that makes sense, seems like tailwindcss would help us. Feel free to add additional commits to this PR and make sure that the navbar works well on both desktop and mobile. Personally I don't think the navbar should be vertically stacked like that on either desktop or mobile.

**Comment by farque65** [comment]
The network switch and address are no longer stacked on mobile.

**Review by varunv5000 — APPROVED** [review]

**Pull request merged**
