### PR TITLE
[issue-238] Integrate Token List Component and use uniswap token list

### PR DESCRIPTION
**Pull request by farque65**

### CODE REVIEW

**Review by varunv5000 — COMMENTED** [review]
1. I'm getting this bug where it takes a while for the "guest page" to load after clicking the toggle button.
2. I think what we can do is have only 3 tokens permanently on the list: "ETH", "GTC", and the most recent token that was imported, otherwise the list would get too long.
Everything else looks good!

**Comment by farque65** [comment]
> 1. I'm getting this bug where it takes a while for the "guest page" to load after clicking the toggle button.
> 2. I think what we can do is have only 3 tokens permanently on the list: "ETH", "GTC", and the most recent token that was imported, otherwise the list would get too long.
>    Everything else looks good!

The lookup is only available on mainnet right now. So allowing users to keep their own would be good. We should not change that so #2 on the request does not make sense. 

Also the note on the modal should stay so people know that the list is local

**Comment by varunv5000** [comment]
> Also the note on the modal should stay so people know that the list is local

Ehhh, it just seems like it would confuse the user, you're not going to expect that other people to have the same tokens imported just because you did it

**Comment by varunv5000** [comment]
> The lookup is only available on mainnet, arbitrum and optimism right now. So allowing users to keep their own would be good. We should not change that so #2 on the request does not make sense.

One issue I had was that the list of tokens could get too long if you imported too many tokens. Also, there seemed to be  other bugs with that list. My proposal is that only one new token is on that list at a time. So if you import a new token, it gets swapped with the other one on the list. For mainnet, there should be max 3 tokens on that list: ETH, GTC, and the most recent token you imported. For other networks, it can only be 2:  ETH, and the most recent token imported

**Comment by farque65** [comment]
> > Also the note on the modal should stay so people know that the list is local
> 
> Ehhh, it just seems like it would confuse the user, you're not going to expect that other people to have the same tokens imported just because you did it

Thats why we need the note to clarify the list. Eliminate assumptions like the token list being stored for all users in a room

**Review by varunv5000 — APPROVED** [review]

**Comment by varunv5000** [comment]
There was still a loading issue when opening up the token import. Therefore, I added a loading state on the button.

**Pull request merged**
