### PR TITLE
Payout transaction hashes are now colored links

### PR DESCRIPTION
**Pull request by varunv5000**

### CODE REVIEW

**Comment by farque65** [comment]
Screen Shot 2022-01-27 at 9 14 03 AM
Screen Shot 2022-01-27 at 9 15 45 AM
The number the user sees is in scientific notation and the number in ether scan is human readable. This can be confusing for users at a glance. The number would just need to be rounded to 10 digits and we would get a readable number.

**Comment by varunv5000** [comment]
Ehhh thats's not a huge issue, it's very rare someone would send that little amount of eth or tokens

**Comment by varunv5000** [comment]
I think scientific notation works in that rare case

**Comment by farque65** [comment]
I see what you are saying. I tried the same for 0.1 ETH, which returns a long 0.1666666 ETH. This is good but we might have to change it.

**Review by farque65 — APPROVED** [review]

**Pull request merged**
