### PR TITLE
Bug Fix - Updated share room link button placement

### PR DESCRIPTION
**Pull request by farque65**

### CODE REVIEW

**Comment by varunv5000** [comment]
I think there should be a link icon instead of a big button. It takes up too much unnecessary space on the app

**Comment by farque65** [comment]
> I think there should be a link icon instead of a big button. It takes up too much unnecessary space on the app

I had that idea too but would a user recognize it

**Comment by farque65** [comment]
That doesn't make sense. The button is intended to allow someone to copy the current url and share it with someone.

**Comment by varunv5000** [comment]
But the button doesn't look that good

**Comment by farque65** [comment]
> But the button doesn't look that good

Link Icon looks good. I updated the button color

**Pull request merged**
